# Stonecutter
stonecutter_enabled_platforms=fabric
# Java
java.version=21
# Mod properties
mod.aw_version=1.19.4
mod.fabric_range==1.19.4
mod.neoforge_range=[1.19.4]
# Dependency versions
deps.minecraft=1.19.4
deps.parchment=2023.06.26
deps.fabric-loader=0.19.2
deps.fabric-api=0.87.2
deps.neoforge=X
deps.forge=45.4.0
deps.modmenu=9.0.0
