# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

minecraft_version=24w18a
yarn_mappings=24w18a+build.4
loader_version=0.15.11
#Fabric api
fabric_version=0.97.9+1.21
# Mod Properties
mod_version=1.6.1
maven_group=net.kosmo
archives_base_name=fixbookgui