# Gradle
org.gradle.jvmargs=-Xmx4G
# Java
java.version=[VERSIONED]
# Mod properties
mod.name=FixBookGUI
mod.id=fixbookgui
mod.group=net.kosmo
mod.version=2.0.0
mod.license=LGPL-3.0-only
mod.author=KosmoMoustache
mod.description=Fix book gui (MC-61489)
mod.github=https://github.com/KosmoMoustache/FixBookGUI
# Minecraft
minecraft_version=[VERSIONED]
min_minecraft_version=[VERSIONED]
# Mappings
deps.parchment=[VERSIONED]
# Stonecutter
stonecutter_enabled_platforms=fabric, neoforge
# , 1.20.2, 1.20.4, 1.20.6, 1.21, 1.21.1, 1.21.3, 1.21.4, 1.21.5, 1.21.8
stonecutter_enabled_common_versions=1.19.4, 1.20.4
stonecutter_enabled_fabric_versions=1.19.4, 1.20.4
#, 1.20.6, 1.21.1, 1.21, 1.21.3, 1.21.4, 1.21.5, 1.21.8
stonecutter_enabled_neoforge_versions=1.20.4
# Fabric https://fabricmc.net/develop/
deps.fabric-loader=[VERSIONED]
deps.fabric-api=[VERSIONED]
# NeoForge https://projects.neoforged.net/neoforged/neoforge
deps.neoforge=[VERSIONED]
# Dependencies
deps.modmenu=[VERSIONED]