# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.configuration-cache=false
org.gradle.parallel=true
org.gradle.caching=true
# Java
java.version=[JAVA_VERSION_VERSIONED]
# Mod properties
mod.id=fixbookgui
mod.name=FixBookGUI
mod.version=2.1.0
mod.group=net.kosmo
mod.license=LGPL-3.0-only
mod.description=Fix book gui (MC-61489)
mod.github=https://github.com/KosmoMoustache/FixBookGUI
mod.aw_version=[MOD_AW_VERSION_VERSIONED]
mod.fabric_range=[MOD_FABRIC_RANGE_VERSIONED]
mod.neoforge_range=[MOD_NEOFORGE_RANGE_VERSIONED]
# Minecraft
minecraft_version=[VERSIONED]
min_minecraft_version=[VERSIONED]
# Dependency versions
deps.minecraft=[DEPS_MINECRAFT_VERSIONED]
deps.parchment=[DEPS_PARCHMENT_VERSIONED]
# Stonecutter
stonecutter_enabled_platforms=fabric, neoforge
stonecutter_enabled_common_versions=1.19.4, 1.20.2, 1.20.4, 1.20.6, 1.21, 1.21.1, 1.21.3, 1.21.4, 1.21.5, 1.21.8, 1.21.9, 1.21.10, 1.21.11, 26.1, 26.2
stonecutter_enabled_fabric_versions=1.19.4, 1.20.2, 1.20.4, 1.20.6, 1.21, 1.21.1, 1.21.3, 1.21.4, 1.21.5, 1.21.8, 1.21.9, 1.21.10, 1.21.11, 26.1, 26.2
stonecutter_enabled_neoforge_versions=1.20.4, 1.20.6, 1.21, 1.21.1, 1.21.3,1.21.4, 1.21.5, 1.21.8, 1.21.9, 1.21.10, 1.21.11, 26.1, 26.2
# loom-back-compat
loomx.loom_version=1.16-SNAPSHOT
