# Stonecutter
stonecutter_enabled_platforms=fabric, neoforge
# Java
java.version=21
# Mod properties
mod.aw=1.19.4
mod.fabric_range==1.20.6
mod.neoforge_range=[1.20.6]
# Dependency versions
deps.minecraft=1.20.6
deps.parchment=2024.06.16
deps.fabric-loader=0.19.2
deps.fabric-api=0.100.8
deps.neoforge=20.6.139
deps.modmenu=11.0.1
