# Stonecutter
stonecutter_enabled_platforms=fabric, neoforge
# Java
java.version=21
# Minecraft
minecraft_version=1.21.10
min_minecraft_version=1.21.10
# Mappings
deps.parchment=
# Fabric
deps.fabric-loader=0.18.1
deps.fabric-api=0.138.3
# NeoForge
deps.neoforge=21.10.64
# Dependencies
deps.modmenu=16.0.0-rc.1
