# Stonecutter
stonecutter_enabled_platforms=fabric, neoforge
# Java
java.version=21
# Mod properties
mod.aw_version=1.19.4
mod.fabric_range==1.21.5
mod.neoforge_range=[1.21.5]
# Dependency versions
deps.minecraft=1.21.5
deps.parchment=2025.06.15
deps.fabric-loader=0.19.2
deps.fabric-api=0.128.2
deps.neoforge=21.5.97
deps.modmenu=14.0.2
