# Stonecutter
stonecutter_enabled_platforms=fabric, neoforge
# Java
java.version=21
# Minecraft
minecraft_version=1.21.4
min_minecraft_version=1.21.4
# Mappings
deps.parchment=2025.03.23
# Fabric
deps.fabric-loader=0.17.2
deps.fabric-api=0.119.4
# NeoForge
deps.neoforge=21.4.150
# Dependencies
deps.modmenu=13.0.3
