# Stonecutter
stonecutter_enabled_platforms=fabric, neoforge
# Java
java.version=17
# Mod properties
mod.aw=1.19.4
mod.fabric_range==1.20.2
mod.neoforge_range=[1.20.2]
# Dependency versions
deps.minecraft=1.20.2
deps.parchment=2023.12.10
deps.fabric-loader=0.19.2
deps.fabric-api=0.91.6
deps.neoforge=20.2.93
deps.modmenu=10.0.0-beta.1
