# Stonecutter
stonecutter_enabled_platforms=fabric, neoforge
# Java
java.version=21
# Mod properties
mod.aw_version=1.19.4
mod.fabric_range==1.20.4
mod.neoforge_range=[1.20.4]
# Dependency versions
deps.minecraft=1.20.4
deps.parchment=2024.04.14
deps.fabric-loader=0.19.2
deps.fabric-api=0.97.3
deps.neoforge=20.4.251
deps.modmenu=11.0.0-beta.1
