name: Publish on Curseforge & Modrinth

on: [ workflow_dispatch ]

env:
  MINECRAFT_VERSION: 1.19.2
  JAVA_VERSION: 17
  RELEASE_NAME: FixBookGUI
  RELEASE_VERSION: 1.1

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Publish (CurseForge/Modrinth)
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          curseforge-id: 811449
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          
          modrinth-id: myKgAJq6
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          github-token: ${{ secrets.P_GITHUB_TOKEN }}
          github-tag: v${{ env.MINECRAFT_VERSION}}-${{ env.RELEASE_VERSION }}

          game-versions: |
            1.19.2
          loaders: fabric
          name: "${{env.RELEASE_NAME}} ${{env.RELEASE_VERSION}}"
          version-type: release
          changelog-file: CHANGELOG.md
          files: build/libs/!(*-@(dev|sources|javadoc)).jar
