name: Publish on Curseforge & Modrinth

on: [ pull_request, workflow_dispatch ]

env:
  MINECRAFT_VERSION: 1.19.2
  JAVA_VERSION: 17
  RELEASE_NAME: FixBookGUI
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
  CURSEFORGE_TOKEN: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Publish (CurseForge/Modrinth)
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          curseforge-id: 811449
          curseforge-token: "${{env.CURSEFORGE_TOKEN}}"

          modrinth-id: myKgAJq6
          modrinth-token: "${{env.MODRINTH_TOKEN}}"

#          github-tag: "v${{env.VERSION}}"
#          github-token: "${{env.GITHUB_TOKEN}}"

          name: "${{env.RELEASE_NAME}}"
          version-type: release
          changelog-file: CHANGELOG.md

          files-primary: build/libs/*-@(sources).jar

          loaders: fabric
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"